---
- name: setup node
  hosts: all
  tasks:

  - name: update all packages
    yum:
      name: '*'
      state: latest

  - name: install network tools
    yum:
      name: net-tools
 
  - name: turn off firewall for install
    command: systemctl disable firewalld
    become: yes

  - name: creates .ssh directory
    file: path=~/.ssh state=directory owner=centos group=centos mode=700

  - name: copy public key to authorized keys
    template: 
      src: ~/.ssh/id_rsa.pub 
      dest: "~/.ssh/authorized_keys"
      owner: centos
      group: centos
      mode: 0640

  - replace:
      path: /etc/sudoers
      regexp: '^#\s*%wheel\s*ALL=\(ALL\)\s*NOPASSWD:\s*ALL$'
      replace: '%wheel        ALL=(ALL)       NOPASSWD: ALL'
    become: yes

  - replace:
      path: /etc/sudoers
      regexp: '^%wheel\s*ALL=\(ALL\)\s*ALL$'
      replace: '# %wheel  ALL=(ALL)       ALL'
    become: yes

  - replace:
      path: /etc/fstab
      regexp: '^/dev/mapper/centos-swap\s*swap\s*swap\s*defaults\s*[0-9]\s*[0-9]$'
      replace: '# /dev/mapper/centos-swap swap                    swap    defaults        0 0'
    become: yes  

  - name: restart server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
    become: yes
